# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Actis(object):
    def setupUi(self, Actis):
        Actis.setObjectName("Actis")
        Actis.resize(443, 218)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Actis.sizePolicy().hasHeightForWidth())
        Actis.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Alien.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Actis.setWindowIcon(icon)
        Actis.setStyleSheet("QDialog{background-color: qconicalgradient(cx:0.38, cy:0.556, angle:79, stop:0.149254 rgba(192, 189, 255, 255), stop:0.437811 rgba(186, 186, 186, 255), stop:0.641791 rgba(245, 255, 178, 255), stop:0.850746 rgba(186, 186, 186, 255))\n"
"};\n"
"\n"
"")
        self.fichero_Excel = QtWidgets.QLineEdit(Actis)
        self.fichero_Excel.setGeometry(QtCore.QRect(20, 34, 341, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fichero_Excel.sizePolicy().hasHeightForWidth())
        self.fichero_Excel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fichero_Excel.setFont(font)
        self.fichero_Excel.setStyleSheet("QLineEdit{color:rgb(0, 85, 255)}")
        self.fichero_Excel.setText("")
        self.fichero_Excel.setFrame(True)
        self.fichero_Excel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.fichero_Excel.setClearButtonEnabled(False)
        self.fichero_Excel.setObjectName("fichero_Excel")
        self.botonBrowse = QtWidgets.QPushButton(Actis)
        self.botonBrowse.setGeometry(QtCore.QRect(370, 34, 41, 41))
        self.botonBrowse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.botonBrowse.setStyleSheet("background-color: rgb(129, 129, 129);")
        self.botonBrowse.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonBrowse.setIcon(icon1)
        self.botonBrowse.setObjectName("botonBrowse")
        self.boton_OK = QtWidgets.QPushButton(Actis)
        self.boton_OK.setGeometry(QtCore.QRect(190, 150, 93, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.boton_OK.setFont(font)
        self.boton_OK.setStyleSheet("background-color:rgb(203, 203, 203)")
        self.boton_OK.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Apply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_OK.setIcon(icon2)
        self.boton_OK.setIconSize(QtCore.QSize(24, 24))
        self.boton_OK.setObjectName("boton_OK")
        self.boton_Cancel = QtWidgets.QPushButton(Actis)
        self.boton_Cancel.setGeometry(QtCore.QRect(320, 150, 93, 41))
        self.boton_Cancel.setStyleSheet("background-color:rgb(203, 203, 203)")
        self.boton_Cancel.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Cancel.setIcon(icon3)
        self.boton_Cancel.setIconSize(QtCore.QSize(24, 24))
        self.boton_Cancel.setObjectName("boton_Cancel")
        self.avisos = QtWidgets.QLineEdit(Actis)
        self.avisos.setGeometry(QtCore.QRect(22, 100, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.avisos.setFont(font)
        self.avisos.setAlignment(QtCore.Qt.AlignCenter)
        self.avisos.setObjectName("avisos")

        self.retranslateUi(Actis)
        QtCore.QMetaObject.connectSlotsByName(Actis)

    def retranslateUi(self, Actis):
        _translate = QtCore.QCoreApplication.translate
        Actis.setWindowTitle(_translate("Actis", "Procesado Excel"))
        self.fichero_Excel.setPlaceholderText(_translate("Actis", "                Fichero Excel"))
import icons_rc
